### ISSUE TITLE
Go through Google Places API and see if we can use it to get good images

### ISSUE THREAD

**Issue by EdenShapiro** [codepath17-g7/chatspot#15]
https://cocoapods.org/pods/GooglePlaces 
https://developers.google.com/places/ios-api/start

**Comment by roostertech** [comment]
For demo purpose, we will just find good image for each location and statically set it.

**Comment by EdenShapiro** [comment]
@roostertech i'm picking neighborhood in mountain view, rengstorff park, MinuteMaid Park in Houston to peak in on the World Series game, and facebook. i’ll make a few static extras too, just let me know which. i'll start when i have your confirmation, since creating all the properly sized images is somewhat time-consuming

**Comment by EdenShapiro** [comment]
done
