### ISSUE TITLE
Around me room message to indicate room transition

### ISSUE THREAD

**Issue by roostertech** [codepath17-g7/chatspot#34]

**Comment by roostertech** [comment]
I added rough support for this feature. The system message is logged by cloud function on each transition and flagged with system = true. I added it with a basic cell to the chat list (flipped).

**Comment by EdenShapiro** [comment]
I can't find the code for this. Where is this added? @roostertech

**Comment by roostertech** [comment]
ChatRoomVC:360

**Comment by EdenShapiro** [comment]
Done
