### ISSUE TITLE
Infinite scroll in chatrooms appears to be broken

### ISSUE THREAD

**Issue by EdenShapiro** [codepath17-g7/chatspot#48]

**Comment by hakeemsyd** [comment]
Can you explain what's broken and how to repro

**Comment by EdenShapiro** [comment]
When you scroll to the top, there is a flicker and glitchy reloading of the table (and not necessarily adding of new rows) and puts the scroller back in the middle of the table

**Comment by roostertech** [comment]
So when you have reached the top of the table, each query will return one row, which is removed after sorting. So the table will reload with out any change = flicker.
